In [1]:
import numpy as np

1.Create a function to check whether numpy array has Zero values or not.

In [2]:
def contains_zeroes(arr):
    zeroes = np.count_nonzero(arr)
    if zeroes == 0:
        return True
    else:
        return False

In [3]:
a = np.array([1, 2, 3, 0, 2])
print(contains_zeroes(a))

False


2.Consider an array contains marks of students. Find the median and mean of students who got passing marks.

In [4]:
def get_marks_stats(marks, pass_marks = 40):
    pass_students = marks[np.where(marks >= pass_marks)]
    return (np.median(pass_students), np.mean(pass_students))

In [5]:
marks = np.random.randint(low=0, high=100, size=100)
median_marks, mean_marks = get_marks_stats(marks)
print('Median :  {}, Mean : {}'.format(median_marks, mean_marks))

Median :  71.5, Mean : 71.61666666666666


3.Consider an array containing date of birth of students (Use `np.datetime64('2018-02-01')`). Find the age of all students. If age is 18 label it First, if it is 19, label it Second, if it is 20, label it Third, if it is 21, label it Fourth.

In [6]:
def get_my(date):
    return list(map(np.int64, [np.datetime64(date, 'M'), np.datetime64(date, 'Y')]))

In [7]:
def calc_age(dob):
    present = np.datetime64('today')
    m_dob, y_dob = get_my(dob)
    m_present, y_present = get_my(present)
    age_y = y_present - y_dob
    if dob != present:
        age_y -= 1
    return max(0, age_y-17)

In [8]:
def get_label(dates):
    labels = np.array([calc_age(x) for x in dates])
    labels_dict = {1: 'First', 2: 'Second', 3: 'Third', 4: 'Fourth', 5: 'Fifth'}
    return [labels_dict[x] for x in labels]

In [9]:
dates = np.array(['2000-02-10', '1998-06-15', '1997-08-13'], dtype='datetime64')
labels = get_label(dates)
print(labels)

['First', 'Third', 'Fourth']


4.Create a function to sort 2d Array by a column.

In [10]:
def sort_by_col(arr, col_no):
    col_indices = np.argsort(arr[:, col_no])
    sorted_arr = arr[col_indices]
    return sorted_arr

In [11]:
a = np.random.rand(3, 3)
print('Original Array ' ,a)
sorted_arr = sort_by_col(a, 1)
print('Sorted Array ', sorted_arr)

Original Array  [[0.24777163 0.14715234 0.16054522]
 [0.39854582 0.684247   0.29343925]
 [0.31724914 0.84590894 0.66627449]]
Sorted Array  [[0.24777163 0.14715234 0.16054522]
 [0.39854582 0.684247   0.29343925]
 [0.31724914 0.84590894 0.66627449]]


5.Create one hot encoding of an array. For example For an `array([2, 3, 2, 2, 2, 1])` Output should be

   ```
   array([[ 0.,  1.,  0.],

             [ 0.,  0.,  1.],

             [ 0.,  1.,  0.],

             [ 0.,  1.,  0.],

             [ 0.,  1.,  0.],

            [ 1.,  0.,  0.]])
   ```

In [12]:
def one_hot_encode(arr):
    target = arr - 1
    n_values = np.max(target) + 1
    return np.eye(n_values)[target]

In [13]:
a = np.array([2, 3, 2, 2, 2, 1])
print(one_hot_encode(a))

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


6.Drop all missing values from an array Input: `np.array([1,2,3,np.nan,5,6,7,np.nan])` Desired Output: `array([ 1.,2.,3.,5.,6.,7.])`

In [14]:
def remove_nan(arr):
    return arr[np.where(np.logical_not(np.isnan(arr)))]    

In [15]:
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
non_nan = remove_nan(arr)
print(non_nan)

[1. 2. 3. 5. 6. 7.]


7.Find Local maxima from an array. Input: `a = np.array([1, 3, 7, 1, 2, 6, 0, 1])` Desired Output: `array([2, 5])`

In [16]:
def get_max(arr):
    indices = np.arange(0, len(arr)-1, 1)
    local_minimas = []
    
    if arr[0] > arr[1]:
        local_minimas.append(0)
    
    for x in indices:
        if x != 0:
            if arr[x] > arr[x-1] and arr[x] > arr[x+1]:
                local_minimas.append(x)
    
    if arr[-1] > arr[-2]:
        local_minimas.append(len(arr)-1)
    
    return np.array(local_minimas)

In [17]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
print(get_max(a))

[2 5 7]


8.From the given 1d array arr, generate a 2d matrix using strides,

For example for an `array ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])` with a window length of `w=4` and strides of `s=2`, like `[[0,1,2,3], [2,3,4,5], [4,5,6,7]..]`.
w and s will be provided by user

In [18]:
def get_conv(arr, w, s):
    indices = np.arange(0, len(arr), s)
    mat = []
    for i in indices:
        if i + w < len(arr):
            mat.append(arr[i:i+w])
        else:
            temp = arr[i:]
            diff = w - len(temp)
            temp = np.concatenate((temp, np.zeros(diff, np.int64)), axis=0)
            mat.append(temp)
    return np.array(mat)

In [19]:
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
print(get_conv(a, 4, 2))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]
 [12 13 14  0]
 [14  0  0  0]]
